name: Run Luacheck

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          config: https://raw.githubusercontent.com/Kozoaku/wow-luacheckrc/mainline/.luacheckrc