name: Project Managment

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    name: Add triage label to issue
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.2
        with:
          repo-token: ${{ secrets.PROJECT_MANAGEMENT }}
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0

  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Kozoaku/projects/1
          github-token: ${{ secrets.PROJECT_MANAGEMENT }}
          labeled: needs-triage
