name: Create new version

on:
  push:
    branches: ['main', 'beta', 'alpha']

jobs:
  luacheck:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Luacheck
        continue-on-error: true
        uses: nebularg/actions-luacheck@v1

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install Semantic Release
        run: |
          npm install semantic-release @semantic-release/git @sementic-release/changelog -D
      - name: Create new version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ github.event.pusher.name }}
          GIT_AUTHOR_EMAIL: ${{ github.event.pusher.email }}
        run: |
          npx semantic-release
