name: Create Release

on:
  push:
    branches:
      - 'main'

jobs:
  releaes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: true
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: "Kozoaku"
          GIT_AUTHOR_EMAIL: "93962386+Kozoaku@users.noreply.github.com"
          GIT_COMMITTER_NAME: "Kozoaku"
          GIT_COMMITTER_EMAIL: "93962386+Kozoaku@users.noreply.github.com"
        run: npx semantic-release
