name: version
run-name: Create new ${{ github.ref_name }} version 
on:
  push:
    branches: ['main', 'beta', 'alpha']
    paths-ignore: ['.github/**', 'docs/**']

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install Semantic Release
        run: |
          npm install semantic-release @semantic-release/git @semantic-release/changelog -D
      - name: Create new version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ github.event.pusher.name }}
          GIT_AUTHOR_EMAIL: ${{ github.event.pusher.email }}
        run: |
          npx semantic-release
